# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MyProject' do
  inhibit_all_warnings!
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'KakaJSON'
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'SSZipArchive'
  # Pods for MyProject

end
